// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1C3ezEaQYupoDiT-Q_MW5P0HNsjFRZsA',
    appId: '1:105709893756:web:eff3d93a8203fee36a71f9',
    messagingSenderId: '105709893756',
    projectId: 'yet-foods-28a8d',
    authDomain: 'yet-foods-28a8d.firebaseapp.com',
    storageBucket: 'yet-foods-28a8d.appspot.com',
    measurementId: 'G-TRCBXDVCK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcU3weEnTiqyZ5EDqkPT47AXz3XSP8azU',
    appId: '1:105709893756:android:dd576669b7deef326a71f9',
    messagingSenderId: '105709893756',
    projectId: 'yet-foods-28a8d',
    storageBucket: 'yet-foods-28a8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTbQgalbxr6DaJRDYrAlhuri0O-79lmF4',
    appId: '1:105709893756:ios:db68f6adb3aece066a71f9',
    messagingSenderId: '105709893756',
    projectId: 'yet-foods-28a8d',
    storageBucket: 'yet-foods-28a8d.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTbQgalbxr6DaJRDYrAlhuri0O-79lmF4',
    appId: '1:105709893756:ios:db68f6adb3aece066a71f9',
    messagingSenderId: '105709893756',
    projectId: 'yet-foods-28a8d',
    storageBucket: 'yet-foods-28a8d.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1C3ezEaQYupoDiT-Q_MW5P0HNsjFRZsA',
    appId: '1:105709893756:web:2e9099a207b8d5686a71f9',
    messagingSenderId: '105709893756',
    projectId: 'yet-foods-28a8d',
    authDomain: 'yet-foods-28a8d.firebaseapp.com',
    storageBucket: 'yet-foods-28a8d.appspot.com',
    measurementId: 'G-50E6VCJJ1Y',
  );
}
